### ISSUE TITLE
Question about Instagram API deprecation notices

### ISSUE THREAD

**Issue by circa1977** [jmx2inc/picpuller-for-craft3#13]
I'm eyeing this plugin for an upcoming client project. I started out looking at the Instagram API directly this morning, and noticed a few notices about features being deprecated in favor of the Open Graph API. https://www.instagram.com/developer/

Will this impact this plugin's functionality as documented? We'll be looking to display feeds directly on our Craft website.

Thanks!

**Comment by johnfmorton** [comment]
The changes will affect Pic Puller. 

The Open Graph API as they currently offer it won't be a replacement for what Pic Puller does though. The Open Graph API is for "Instagram business profile users" which are not the primary users of Pic Puller.  The Open Graph API mentions support for "Business Discovery API", "Insights API", and "Comment Moderation API". These things are not things Pic Puller does.

Pic Puller uses the "Basic" access which Facebook says "will be available until early 2020". 

Facebook has promised for months that a replacement for that would be coming in "early 2019" but that language has disappeared from their transition documentation. 

My plans for Pic Puller, dependent on how Facebook does the rollout of the API, are to continue making Pic Puller for Craft and come up with some transition to the new API. Since Facebook has not released details on how the new API will work though, I'm just waiting and hoping for the best.
